// generated by chatgpt
using CsvHelper;
using CsvHelper.Configuration;
using CsvHelper.TypeConversion;
using ScheduleLib.Helper;
using static System.Enum;

namespace ScheduleLib.Application.Core.Topics;

public sealed class EnumConverterOptions<T> where T : struct, Enum
{
    internal List<T>? Included { get; private set; }
    internal List<T>? Ignored { get; private set; }

    public void Include(T value)
    {
        if (Ignored != null)
        {
            throw new InvalidOperationException("Cannot include when ignoring");
        }
        Included ??= new();
        Included.Add(value);
    }

    public void Ignore(T value)
    {
        if (Included != null)
        {
            throw new InvalidOperationException("Cannot ignore when including");
        }
        Ignored ??= new();
        Ignored.Add(value);
    }
}

public sealed class ConfigurableEnumConverter<T> : DefaultTypeConverter
    where T : struct, Enum
{
    private readonly HashSet<string> _allowedNames;

    public ConfigurableEnumConverter(EnumConverterOptions<T> options)
    {
        var allValues = GetValues(typeof(T)).Cast<T>();

        // Always exclude Invalid and Count
        var filtered = allValues.Where(v =>
        {
            var name = v.ToString();
            return name != "Invalid" && name != "Count";
        });

        IEnumerable<T> final;

        // Include → whitelist mode
        if (options.Included != null)
        {
            final = options.Included;
        }
        else if (options.Ignored != null)
        {
            final = filtered.Where(v => !options.Ignored.Contains(v));
        }
        else
        {
            final = new EnumMembers<T>();
        }

        _allowedNames = final
            .Select(v => v.ToString())
            .ToHashSet(StringComparer.Ordinal);
    }

    public override object ConvertFromString(string? text, IReaderRow row, MemberMapData memberMapData)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            throw new TypeConverterException(this, memberMapData, text, row.Context,
                $"Empty value is not allowed for enum {typeof(T).Name}.");
        }

        // Disallow numeric values
        if (int.TryParse(text, out _))
        {
            throw new TypeConverterException(this, memberMapData, text, row.Context,
                $"Numeric value '{text}' is not allowed for enum {typeof(T).Name}.");
        }

        if (!_allowedNames.Contains(text))
        {
            throw new TypeConverterException(this, memberMapData, text, row.Context,
                $"Value '{text}' is not allowed for enum {typeof(T).Name}. " +
                $"Allowed values: {string.Join(", ", _allowedNames)}");
        }

        return Parse(typeof(T), text, ignoreCase: false);
    }
}

public static class EnumConverterExtensions
{
    public static MemberMap<TClass, TMember> EnumConverter<TClass, TMember>(
        this MemberMap<TClass, TMember> map,
        Action<EnumConverterOptions<TMember>>? configure = null)
        where TMember : struct, Enum
    {
        var opts = new EnumConverterOptions<TMember>();
        configure?.Invoke(opts);

        return map.TypeConverter(new ConfigurableEnumConverter<TMember>(opts));
    }
}
