<Project>
    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootPath>$(MSBuildThisFileDirectory)</RootPath>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <PropertyGroup>
        <ProjectPathRelative>$([System.IO.Path]::GetRelativePath('$(RootPath)', '$(MSBuildProjectDirectory)'))</ProjectPathRelative>
        <ProjectPathRelativeNorm>$([System.String]::Copy('$(ProjectPathRelative)').Replace('\','/'))</ProjectPathRelativeNorm>
        <IsTestsProject>$([System.Text.RegularExpressions.Regex]::IsMatch('$(ProjectPathRelativeNorm)', '(^|/)Tests(/|$)'))</IsTestsProject>
    </PropertyGroup>

    <PropertyGroup>
        <MicrosoftPackagesVersion>10.0.1</MicrosoftPackagesVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsScheduleIntegrationTest)' == 'true'">
    </PropertyGroup>
</Project>
