<Project>
    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootPath>$(MSBuildThisFileDirectory)</RootPath>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <PropertyGroup>
        <ProjectPathRelative>$([System.IO.Path]::GetRelativePath('$(RootPath)', '$(MSBuildProjectDirectory)'))</ProjectPathRelative>
        <ProjectPathRelativeNorm>$([System.String]::Copy('$(ProjectPathRelative)').Replace('\','/'))</ProjectPathRelativeNorm>
        <IsTestProject>$([System.Text.RegularExpressions.Regex]::IsMatch('$(ProjectPathRelativeNorm)', '(^|/)Tests(/|$)'))</IsTestProject>
    </PropertyGroup>
    <Target Name="Print" BeforeTargets="Build">
        <Message Importance="high" Text="$(IsTestProject)"></Message>
    </Target>

    <PropertyGroup>
        <MicrosoftPackagesVersion>10.0.1</MicrosoftPackagesVersion>
    </PropertyGroup>

</Project>
