<Project>
    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootPath>$(MSBuildThisFileDirectory)</RootPath>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    </PropertyGroup>

    <PropertyGroup>
        <MicrosoftPackagesVersion>10.0.1</MicrosoftPackagesVersion>
    </PropertyGroup>
</Project>
