<Project>
    <ItemGroup>
        <None Include="$(ProjectDir)data\**\*.*" CopyToOutputDirectory="Always" />
    </ItemGroup>

    <ItemGroup Condition="'$(IncludeHelpers)' == 'true'">
        <Using Include="ScheduleLib.UnreachableHelper" Static="true" />
        <ProjectReference
            Condition="'$(MSBuildProjectFullPath)' != '$(RootPath)src\ScheduleLib\ScheduleLib.Helper\ScheduleLib.Helper.csproj'"
            Include="$(RootPath)src\ScheduleLib\ScheduleLib.Helper\ScheduleLib.Helper.csproj" />
<!--        <PackageReference Include="Anton.AutoConstructor.SourceGenerator" Version="1.0.3" />-->
    </ItemGroup>

    <Import Project="$(RootPath)build\Test.targets" Condition="'$(IsTestsProject)' == 'true'"/>
</Project>
