<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(FeaturesPath)OnlineRegistry\OnlineRegistry.csproj" />
        <ProjectReference Include="$(FeaturesPath)LayeredData\Anton.LayeredData.csproj" />
        <ProjectReference Include="$(FeaturesPath)LayeredConfig\LayeredConfig.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="$(MicrosoftPackagesVersion)" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="$(MicrosoftPackagesVersion)" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
        <PackageReference Include="Google.Apis.Drive.v3" Version="1.73.0.4045" />
    </ItemGroup>
</Project>
