<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ScrapingCommon\ScrapingCommon.csproj" />
        <ProjectReference Include="..\ScheduleLib\ScheduleLib.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp.Xml" Version="1.0.0" />
    </ItemGroup>
</Project>
