<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\ScheduleDefaults\ScheduleDefaults.csproj" />
        <ProjectReference Include="..\..\ScheduleLib\ScheduleLib.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Update="LessonParserTests.LexerTest.verified.json">
        <DependentUpon>LessonParserFactoryTests.cs</DependentUpon>
      </None>
    </ItemGroup>
</Project>
