<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(WindowsTarget)</TargetFramework>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CurriculumShared\CurriculumShared.csproj" />
        <ProjectReference Include="..\ConvertDocToDocxLibrary\ConvertDocToDocxLibrary.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="TextCopy" Version="6.2.1" />
        <PackageReference Include="Microsoft.Identity.Web" Version="4.9.0" />
        <PackageReference Include="Microsoft.Graph" Version="4.54.0" />
    </ItemGroup>
</Project>
