<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="NSwag.CodeGeneration.CSharp" Version="14.3.0" />
        <PackageReference Include="NSwag.Generation" Version="14.3.0"/>
        <PackageReference Include="CommandDotNet" Version="7.0.4" />
    </ItemGroup>
</Project>
