<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(WindowsTarget)</TargetFramework>
        <IsScheduleIntegrationTest>true</IsScheduleIntegrationTest>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\ScheduleDefaults\ScheduleDefaults.csproj" />
        <ProjectReference Include="..\..\OnlineRegistry\OnlineRegistry.csproj" />
    </ItemGroup>

    <Import Project="$(RootPath)build\UserSecrets.props" />

    <ItemGroup>
        <PackageReference Include="Moq" Version="4.20.72" />
    </ItemGroup>
</Project>
