<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(WindowsTarget)</TargetFramework>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(RootPath)src\ScheduleLib\ScheduleLib.Generator.Pdf\ScheduleLib.Generator.Pdf.csproj" />
        <ProjectReference Include="$(RootPath)src\ScheduleLib\ScheduleLib.Helper.Excel\ScheduleLib.Helper.Excel.csproj" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="$(RootPath)src\ScheduleDefaults\ScheduleDefaults.csproj" />

        <ProjectReference Include="$(FeaturesPath)FmiWebsiteInterop\FmiWebsiteInterop.csproj" />
        <ProjectReference Include="$(FeaturesPath)OnlineRegistry\OnlineRegistry.csproj" />
        <ProjectReference Include="$(FeaturesPath)CurriculumDownload\CurriculumDownload.csproj" />
        <ProjectReference Include="$(FeaturesPath)CurriculumShared\CurriculumShared.csproj" />
        <ProjectReference Include="$(FeaturesPath)ConvertDocToDocxLibrary\ConvertDocToDocxLibrary.csproj" />
        <ProjectReference Include="$(FeaturesPath)MoodleInterop\MoodleInterop.csproj" />
        <ProjectReference Include="$(FeaturesPath)LayeredData\Anton.LayeredData.csproj" />
        <ProjectReference Include="$(FeaturesPath)LayeredConfig\LayeredConfig.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None
            Include="data\**\*.docx"
            Exclude="data\**\~$*.docx"
            CopyToOutputDirectory="Always"
            CopyToPublishDirectory="Always" />
        <None
            Include="data\**\*.xlsx"
            CopyToOutputDirectory="Always"
            CopyToPublishDirectory="Always" />
        <None
            Include="data\topics\**\*"
            CopyToOutputDirectory="Always"
            CopyToPublishDirectory="Always" />
    </ItemGroup>

    <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
        <PackageReference Include="OpenXmlPowerTools.Core" Version="1.0.0" />
        <PackageReference Include="System.Linq.Async" Version="6.0.1" />
        <PackageReference Include="SpreadCheetah" Version="1.22.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Apis.Calendar.v3" Version="1.73.0.3993" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    </ItemGroup>
</Project>
