<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IncludeHelpers>true</IncludeHelpers>
        <ImplicitUsings>true</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>Parser.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Anton.AutoConstructor.SourceGenerator" Version="1.0.3" />
        <PackageReference Include="TruePath" Version="1.12.0" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Expressions\" />
    </ItemGroup>
</Project>
