<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LayeredConfig\LayeredConfig.csproj" />
        <ProjectReference Include="..\ThesesParsing\ThesesParsing.csproj" />
    </ItemGroup>
</Project>
