<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <Import Project="$(RootPath)build\UserSecrets.props" />

    <ItemGroup>
        <ProjectReference Include="..\JsonWebsiteSchedule\JsonWebsiteSchedule.csproj" />
        <ProjectReference Include="..\ScheduleLib\ScheduleLib.csproj" />
        <ProjectReference Include="..\ScheduleDefaults\ScheduleDefaults.csproj" />
        <ProjectReference Include="..\OnlineRegistry\OnlineRegistry.csproj" />
        <ProjectReference Include="..\CurriculumDownload\CurriculumDownload.csproj" />
        <ProjectReference Include="..\CurriculumShared\CurriculumShared.csproj" />
        <ProjectReference Include="..\ConvertDocToDocxLibrary\ConvertDocToDocxLibrary.csproj" />
        <ProjectReference Include="..\MoodleInterop\MoodleInterop.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None
            Include="data\**\*.docx"
            Exclude="data\**\~$*.docx"
            CopyToOutputDirectory="Always"
            CopyToPublishDirectory="Always" />
        <None
            Include="data\**\*.xlsx"
            CopyToOutputDirectory="Always"
            CopyToPublishDirectory="Always" />
        <None Update="data\topics\anton\manifest.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\anton\c++.csv">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\anton\design.csv">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\anton\fp.csv">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\tamara\manifest.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\tamara\ДЖ.csv">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\tamara\Информатики.csv">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\nichita\cloud.csv">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\nichita\HTML.csv">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="data\topics\nichita\manifest.json">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
        <PackageReference Include="OpenXmlPowerTools.Core" Version="1.0.0" />
        <PackageReference Include="AngleSharp" Version="1.2.0" />
        <PackageReference Include="System.Linq.Async" Version="6.0.1" />
        <PackageReference Include="SpreadCheetah" Version="1.22.0" />
        <PackageReference Include="ClosedXML" Version="0.105.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Apis.Auth" Version="1.71.0" />
        <PackageReference Include="Google.Apis.Drive.v3" Version="1.71.0.3905" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CsvHelper" Version="33.1.0" />
    </ItemGroup>
</Project>
