<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <RootNamespace>ReaderApp</RootNamespace>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <Import Project="$(RootPath)build\UserSecrets.props" />

    <ItemGroup>
        <ProjectReference Include="..\ScheduleLib\ScheduleLib.csproj" />
        <ProjectReference Include="..\OnlineRegistry\OnlineRegistry.csproj" />
        <ProjectReference Include="..\CurriculumDownload\CurriculumDownload.csproj" />
        <ProjectReference Include="..\CurriculumShared\CurriculumShared.csproj" />
        <ProjectReference Include="..\ConvertDocToDocxLibrary\ConvertDocToDocxLibrary.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None
            Include="data\**\*.docx"
            Exclude="data\**\~$*.docx"
            CopyToOutputDirectory="Always"
            CopyToPublishDirectory="Always" />
        <None
            Include="data\**\*.xlsx"
            CopyToOutputDirectory="Always"
            CopyToPublishDirectory="Always" />
    </ItemGroup>

    <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.1" />
        <PackageReference Include="AngleSharp" Version="1.2.0" />
        <PackageReference Include="System.Linq.Async" Version="6.0.1" />
    </ItemGroup>
</Project>
