<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(WindowsTarget)</TargetFramework>
    </PropertyGroup>

    <Import Project="$(RootPath)build\UserSecrets.props" />

    <ItemGroup>
        <ProjectReference Include="..\Features\Integration\Integration.csproj" />
    </ItemGroup>
</Project>
