<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(WindowsTarget)</TargetFramework>
        <IsScheduleIntegrationTest>true</IsScheduleIntegrationTest>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\MainCli\MainCli.csproj" />
    </ItemGroup>
</Project>
