<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" Version="1.2.0" />

        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.10" />
    </ItemGroup>
</Project>
