<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <InternalsVisibleTo Include="MainCli.Tests" />
    </ItemGroup>

    <PropertyGroup>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <PropertyGroup>
        <!-- Enable to ignore incompatible assembly from the exe proj -->
        <NoWarn>$(NoWarn);NU1702</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <ProjectReference Include="..\ConvertDocToDocx\ConvertDocToDocx.csproj">
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
        <Content Include="..\ConvertDocToDocx\bin\$(Configuration)\net4.8\ConvertDocToDocx.exe">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>
</Project>
