<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IncludeHelpers>true</IncludeHelpers>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Anton.AutoConstructor.SourceGenerator" Version="1.0.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    </ItemGroup>
</Project>
