<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(WindowsTarget)</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\MainCli\MainCli.csproj" />
        <ProjectReference Include="..\ScheduleCommon\ScheduleCommon.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Include="*.verified.*" CopyToOutputDirectory="Always" />
      <None Include="schedule_*.json" CopyToOutputDirectory="Always" />
    </ItemGroup>
</Project>


