<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="$(RootPath)build\UserSecrets.props" />

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CurriculumDownload\CurriculumDownload.csproj" />
    </ItemGroup>
</Project>
